language: node_js
os: linux
dist: focal
node_js:
  - 18
deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  local_dir: public
  keep_history: true
  on:
    branch: main
cache:
  directories:
    - node_modules
script:
  - npm run build
