language: node_js
os: linux
node_js:
  - stable
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: public
  keep-history: true
  on:
    branch: master
cache:
  directories:
    - node_modules
script:
  - npm run build
